name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    if:
      github.event.action == 'assigned'
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: TecWeb
          column: In Progress
          repo-token: ${{ secrets.TOKEN_MAGIKO }}
